import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/Header.jsx'
import Lectorqr from './lectorqr.js'


export default function Home() {



  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header titulo='Control de Invitados' />
      <div className='nav'>
        <Link href='/listaInvitados'><a className='enlace'>Editar Lista de invitados</a></Link>
      </div>
      <div className='nav'>
        <Link href='/lectorqr'><a className='enlace'>Verificacion de Codigos QR</a></Link>
      </div>

    </div>
  )
}
