import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/Header.jsx'


export default function Home() {
  


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header titulo='Control de Invitados' />
      <div className='nav'>
        <Link href='/admin/listaInvitados'><a className='enlace'>Editar Lista de invitados</a></Link>
        <Link href='/editarGrupos'><a className='enlace'>Editar Grupos</a></Link>
        <Link href='/editarMesas'><a className='enlace'>Editar Mesas</a></Link>
      </div>
      
    </div>
  )
}
